# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: build and load ice driver
  block:
    - name: set facts
      set_fact:
        driver_name: "{{ _ice_name }}"
        driver_version: "{{ _ice_ver }}"
        driver_url: "{{ _ice_url }}"
        driver_checksum: "{{ _ice_chksm }}"
        current_mgmt_driver: "{{ _mgmt_driver }}"

    - name: build ice driver
      include_role:
        name: baseline_ansible/infrastructure/build_nic_drivers

- name: build and load iavf driver
  block:
    - name: set facts
      set_fact:
        driver_name: "{{ _iavf_name }}"
        driver_version: "{{ _iavf_ver }}"
        driver_url: "{{ _iavf_url }}"
        driver_checksum: "{{ _iavf_chksm }}"
        current_mgmt_driver: "{{ _mgmt_driver }}"

    - name: build iavf driver
      include_role:
        name: baseline_ansible/infrastructure/build_nic_drivers
