# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: include prometheus-statsd-exporter variables
  include_vars: ../defaults/main.yml

- name: remove prometheus-statsd-exporter chart template directory
  file:
    path: "{{ _statsd_exporter_chart_dir }}"
    state: absent

- name: uninstall prometheus-statsd-exporter using Helm
  command: "helm uninstall statsd-exporter --namespace telemetry"
  changed_when: true
  failed_when: false
