# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
- hosts: controller_group:edgenode_group
  tasks:
  - name: setup baseline_ansible project
    include_tasks: ./roles/infrastructure/setup_baseline_ansible/tasks/main.yml

- hosts: controller_group
  tasks:
  # following roles are not cleaned up directly, they're cleaned when Kubernetes cluster is reset
  # - nfd
  # - multus

  - name: load harbor_registry variables
    include_vars: ./roles/kubernetes/harbor_registry/controlplane/defaults/main.yml

  - name: cleanup harbor_registry
    include_tasks: ./roles/kubernetes/harbor_registry/controlplane/tasks/cleanup.yml

  - name: grafana cleanup
    include_tasks: ./roles/telemetry/grafana/tasks/cleanup.yml
    when: telemetry_grafana_enable | default(True)

  - name: Node Feature Discovery cleanup
    block:
    - name: load nfd variables
      include_vars: ./roles/kubernetes/nfd/defaults/main.yml
    - name: cleanup nfd
      include_tasks: ./roles/kubernetes/nfd/tasks/cleanup.yml
    when: ne_nfd_enable | default(False)

  - name: cleanup prometheus
    include_tasks: ./roles/telemetry/prometheus/tasks/cleanup.yml
    when: telemetry_prometheus_enable | d(True)

  - name: cleanup prometheus-statsd-exporter
    include_tasks: ./roles/telemetry/statsd-exporter/tasks/cleanup.yml
    when: telemetry_statsd_exporter_enable | d(True)

  - name: cleanup cAdvisor
    include_tasks: ./roles/telemetry/cadvisor/tasks/cleanup.yml
    when: telemetry_cadvisor_enable | d(True)

  - name: cleanup telemetry certificates
    include_tasks: ./roles/telemetry/certs/tasks/cleanup.yml

  - name: cleanup multus-cni
    include_tasks: ./roles/kubernetes/cni/multus/controlplane/tasks/cleanup.yml

  - name: helm cleanup
    block:
    - name: load helm variables
      include_vars: ./roles/kubernetes/helm/defaults/main.yml
    - name: cleanup helm
      include_tasks: ./roles/kubernetes/helm/tasks/cleanup.yml

  - name: run CNIs cleanup
    include_tasks: ./roles/kubernetes/cni/tasks/cleanup.yml
    vars:
      - role_path: "{{ playbook_dir }}/roles/kubernetes/cni"

  - name: helm cleanup
    block:
    - name: load helm variables
      include_vars: ./roles/kubernetes/helm/defaults/main.yml
    - name: cleanup helm
      include_tasks: ./roles/kubernetes/helm/tasks/cleanup.yml

  - name: cleanup kubernetes
    include_tasks: ./roles/kubernetes/controlplane/tasks/cleanup.yml

  - name: load kubernetes variables
    include_vars: ./roles/kubernetes/install/defaults/main.yml

  - name: uninstall kubernetes
    include_tasks: ./roles/kubernetes/install/tasks/uninstall.yml

  - name: load docker variables
    include_vars: ./roles/infrastructure/docker/defaults/main.yml

  - name: prune docker
    include_tasks: ./roles/infrastructure/docker/tasks/prune.yml

  - name: uninstall docker
    include_tasks: ./roles/infrastructure/docker/tasks/uninstall.yml

  - name: load golang variables
    include_vars: ./roles/baseline_ansible/infrastructure/install_golang/defaults/main.yml

  - name: cleanup | include golang cleanup.yml
    include_tasks: ./roles/baseline_ansible/infrastructure/install_golang/tasks/cleanup.yml

  - block:
      - name: load git variables
        include_vars: ./roles/infrastructure/git_repo/defaults/main.yml

      - name: cleanup git repos
        include_tasks: ./roles/infrastructure/git_repo/tasks/cleanup.yml

  - name: cleanup git
    yum:
      name: git*
      state: absent
    become: true

  - name: cleanup directory tree
    include_tasks: ./roles/infrastructure/os_setup/tasks/cleanup_directory_tree.yml

- hosts: edgenode_group
  serial: 1
  tasks:
    # biosfw/node - no clean up, because build image is deleted when running docker's prune.yml

    - name: cleanup kubernetes
      include_tasks: ./roles/kubernetes/node/tasks/cleanup.yml

    - name: run CNIs cleanup
      include_tasks: ./roles/kubernetes/cni/tasks/cleanup.yml
      vars:
        - role_path: "{{ playbook_dir }}/roles/kubernetes/cni"

    - name: load kubernetes variables
      include_vars: ./roles/kubernetes/install/defaults/main.yml

    - name: uninstall kubernetes
      include_tasks: ./roles/kubernetes/install/tasks/uninstall.yml

    - name: load docker variables
      include_vars: ./roles/infrastructure/docker/defaults/main.yml

    - name: prune docker
      include_tasks: ./roles/infrastructure/docker/tasks/prune.yml

    - name: uninstall docker
      include_tasks: ./roles/infrastructure/docker/tasks/uninstall.yml

    - name: load golang variables
      include_vars: ./roles/baseline_ansible/infrastructure/install_golang/defaults/main.yml

    - name: cleanup golang
      include_tasks: ./roles/baseline_ansible/infrastructure/install_golang/tasks/cleanup.yml

    - name: load git variables
      include_vars: ./roles/infrastructure/git_repo/defaults/main.yml

    - name: cleanup git
      include_tasks: ./roles/infrastructure/git_repo/tasks/cleanup.yml

    - name: load harbor_registry variables
      include_vars: ./roles/kubernetes/harbor_registry/controlplane/defaults/main.yml

    - name: cleanup harbor_registry certificate
      include_tasks: ./roles/kubernetes/harbor_registry/node/tasks/cleanup.yml

    - name: cleanup directory tree
      include_tasks: ./roles/infrastructure/os_setup/tasks/cleanup_directory_tree.yml

- hosts: edgenode_group
  tasks:
  - name: reboot nodes
    reboot:
    become: true

- hosts: controller_group
  tasks:
  - name: reboot controller
    reboot:
    become: true
