# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
- name: new kernel cmdline from default and additional grub params
  set_fact:
    new_kernel_cmdline: "{{ (default_grub_params + ' ' + additional_grub_params) | trim }}"

- name: set GRUB_CMDLINE_LINUX_DEFAULT variable
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ new_kernel_cmdline }}"'
    insertafter: EOF
  register: grub_lineinfile
  become: true

- name: regenerate grub.cfg  # noqa no-handler
  include_role:
    name: infrastructure/update_grub
  when: grub_lineinfile.changed

- name: Flush handlers
  meta: flush_handlers
