# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: get current kernel params
  command: cat /proc/cmdline
  register: kernel_params
  changed_when: false

- name: get the default variables
  include_vars:
    file: ../defaults/main.yml
    name: default_grub_vars

- name: print grub params
  debug:
    msg:
     - "current: '{{ kernel_params.stdout }}'"
     - "default_grub_params: '{{ default_grub_params | default(default_grub_vars.default_grub_params) }}'"
     - "additional_grub_params: '{{ additional_grub_params | default(default_grub_vars.additional_grub_params) }}'"
