# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
- name: remove generated subdirectories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ project_dir }}"
  - "{{ _persistent_volumes_dest }}"
  become: true
