# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: delete certificate from node
  file:
    path: "/etc/docker/certs.d/{{ _registry_ip_address }}:{{ _registry_port }}"
    state: absent
  failed_when: false
