# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
- name: create directory for copying certificate
  file:
    path: /etc/docker/certs.d/{{ _registry_ip_address }}:{{ _registry_port }}
    state: directory
    mode: 0755
  become: true
