# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: load docker-registry variables
  include_vars: "../../controlplane/defaults/main.yml"

- name: cert should be present
  stat:
    path: /etc/docker/certs.d/{{ _registry_ip_address }}:{{ _registry_port }}/harbor.crt
  register: this
  failed_when: not this.stat.exists
