# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

_statsd_exporter_chart_dir: "{{ ne_helm_charts_default_dir }}/prometheus-statsd-exporter"
_statsd_exporter_chart_commit: "prometheus-statsd-exporter-0.3.1"
_statsd_exporter_chart_url:
  "https://raw.githubusercontent.com/prometheus-community/helm-charts/\
  {{ _statsd_exporter_chart_commit }}/charts/prometheus-statsd-exporter/"


_statsd_exporter_chart:
  - ".helmignore"
  - "Chart.yaml"
  - "values.yaml"

_statsd_exporter_chart_templates:
  - "templates/NOTES.txt"
  - "templates/_helpers.tpl"
  - "templates/configmap.yaml"
  # - "templates/deployment.yaml"
  # - "templates/hpa.yaml"
  # - "templates/ingress.yaml"
  # - "templates/service.yaml"
  - "templates/serviceaccount.yaml"
  # - "templates/servicemonitor.yaml"

_statsd_exporter_files:
  - "deployment.yaml"
  - "proxy_configmap.yaml"
  - "service.yaml"

_proxy_server_name: statsd-exporter
_proxy_secret_name: statsd-exporter-tls
