# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
- name: disable kubelet service
  systemd:
    name: kubelet
    enabled: false
    state: stopped
  failed_when: false
  become: true

- name: close firewall ports
  failed_when: false
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: disabled
    immediate: true
  with_items:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250-10252/tcp
  become: true

- name: remove k8s sysctl rules
  block:
    - name: remove k8s sysctl rules
      file:
        path: /etc/sysctl.d/sysctl_k8s.conf
        state: absent
    - name: refresh sysctl
      command: sysctl --system
  become: true

- name: remove proxy for service
  file:
    name: /usr/lib/systemd/system/kubelet.service.d/http-proxy.conf
    state: absent
  become: true

- name: uninstall packages
  yum:
    name: "{{ _kubernetes_packages_to_remove }}"
    state: absent
  become: true

- name: remove repository
  yum_repository:
    name: kubernetes
    state: absent
  become: true

- name: clear yum cache
  command: yum clean metadata
  args:
    warn: false
  changed_when: true

- name: remove CNI directory
  file:
    name: /etc/cni/net.d
    state: absent
  become: true
