# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: check if specified secret exists
  shell: set -o pipefail && kubectl get secrets -n telemetry | grep {{ tls_secret_name }} | wc -l
  changed_when: false
  register: secrets_found
  failed_when: secrets_found.rc | int > 1

- name: create secret if it doesn't exist
  block:
  - name: Create temporary directory
    tempfile:
      state: directory
    register: cert_dir

  - name: create ca folder
    command: "cp -r {{ _telemetry_certs_dest }}/CA {{ cert_dir.path }}/ca"
    changed_when: false

  - name: Create link for root CA
    file:
      src: "{{ cert_dir.path }}/ca/cert.pem"
      path: "{{ cert_dir.path }}/root.pem"
      state: link
      mode: u+rw

  - name: Create the tls files
    command: "{{ project_dir }}/scripts/tls_pair.sh {{ proxy_name }} {{ cert_dir.path }} {{ cert_dir.path }}/ca"
    changed_when: false

  - name: Set permissions for created files
    file:
      path: "{{ cert_dir.path }}/{{ item }}.pem"
      mode: 0644
      state: file
    loop:
      - key
      - cert

  - name: create secret from tls files
    command: "kubectl create secret tls -n telemetry {{ tls_secret_name }} --cert={{ cert_dir.path }}/cert.pem --key={{ cert_dir.path }}/key.pem"
    changed_when: false

  - name: Delete the temporary directory
    file:
      path: "{{ cert_dir.path }}"
      state: absent
  when: secrets_found.stdout | int == 0
