# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

# SR-IOV Network Operator repo values
_sriov_network_operator:
  url: "https://github.com/k8snetworkplumbingwg/sriov-network-operator"
  download_dir: "{{ _sriov_network_operator_root_dir }}/src"
  commit: "c608feee2dd74b4b99e44d4950b3651040e68a65"  # https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/147
  image_tag: "4.9.0"
  resource_prefix: "intel.com"
  enable_admission_controller: "true"
  git_patch: "sriov_network_operator.patch"

# Webhooks certificates values
_sriov_network_operator_certs_dest: "{{ project_dir }}/certs/sriov-network-operator"
_sriov_network_operator_ca_certs_dest: "{{ _sriov_network_operator_certs_dest }}/CA"
_webhook_operator_service_certs_dir: "{{ _sriov_network_operator_certs_dest }}/webhook-operator-service"
_network_resources_injector_certs_dir: "{{ _sriov_network_operator_certs_dest }}/network-resources-injector"

# general variables
makefile_env_path_var: "/usr/local/go/bin:{{ ansible_env.PATH }}"
patching_retries: 30
patching_delay: 10

# skopeo variables
_skopeo:
  url: "https://github.com/containers/skopeo"
  download_dir: "{{ ansible_env.HOME }}/go/src/github.com/containers/skopeo"
  commit: "v1.4.1"
