# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: include certs variables
  include_vars: ../../certs/defaults/main.yml

- name: include grafana variables
  include_vars: ../defaults/main.yml

- name: remove grafana chart template directory
  file:
    path: "{{ _grafana_chart_dir }}"
    state: absent

- name: remove grafana dashboard directory
  file:
    path: "{{ _grafana_dashboards_conf }}"
    state: absent

- name: remove grafana provisioning directory
  file:
    path: "{{ _grafana_dashboards_prov }}"
    state: absent

- name: close grafana port
  failed_when: false
  firewalld:
    port: 32000/tcp
    permanent: true
    state: disabled
    immediate: true
  become: true

- name: uninstall grafana using Helm
  command: "helm uninstall grafana --namespace telemetry"
  changed_when: true
  failed_when: false

- name: delete definitions of persistent volumes
  command: "kubectl delete pv {{ item }} -n telemetry"
  with_items: "{{ _pv_names }}"
  changed_when: true
  failed_when: false

- name: delete directory for persistent volumes
  file:
    path: "{{ _pv_dir }}"
    state: absent
  become: true
