# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---
- name: remove temporary gitconfig
  file:
    path: "{{ project_dir }}/.smartedge_gitconfig"
    state: absent

- name: remove include in gitconfig
  blockinfile:
    path: "{{ ansible_env.HOME }}/.gitconfig"
    state: absent
    block: |
      [include]
        path = {{ project_dir }}/.smartedge_gitconfig
