# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: create temporary custom .smartedge_gitconfig
  include_tasks: ./gitconfig_bootstrap.yml

- name: online mode
  block:
    - name: check if GitHub token exists
      debug:
        msg: "using git token for repository checkout"
      when: git_repo_token|length > 0

    - name: Set Git Repo URL
      set_fact:
        git_repo_url: "{{ hostvars[groups['controller_group'][0]]['ansible_host'] }}:{{ _offline_package_path }}/github/edgeservices/"
      when: offline_enable | default(false)

    - name: make sure project directory exists
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: 0777
        owner: "{{ ansible_user }}"
      become: true

    - name: checkout clean repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ _git_repo_dest }}"
        version: "{{ git_repo_branch }}"
        accept_hostkey: true
        force: true
      when: always_clean_repository

    - name: make sure repository exists
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ _git_repo_dest }}"
        version: "{{ git_repo_branch }}"
        accept_hostkey: true
        update: false
      when: not always_clean_repository
  when: git_repo_enable | default(false)

  always:
    - name: remove .smartedge_gitconfig
      include_tasks: ./gitconfig_remove.yml
