# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: update cache
  package:
    update_cache: true
  become: true

- name: install docker OS dependencies and role utils
  package:
    name: "{{ _docker_os_dependencies }}"
    state: present
  become: true

- name: install OS specific
  include_tasks: "install_{{ ansible_os_family|lower }}.yml"

- name: install Docker CE
  package:
    name: "{{ _docker_packages }}"
    state: present
  notify:
    - enable and start docker service
  become: true

- name: change docker completion url if offline mode
  set_fact:
    _docker_completion_url: "https://{{ hostvars[groups['controller_group'][0]]['ansible_host'] }}/docker"
    _docker_compose_completion_url: "https://{{ hostvars[groups['controller_group'][0]]['ansible_host'] }}/docker-compose"
  when: offline_enable | default(False)

- name: setup docker bash completion
  block:
    - name: download Docker CLI bash completion
      get_url:
        url: "{{ _docker_completion_url }}"
        dest: "/etc/bash_completion.d"
      become: true
      register: result
      retries: "{{ number_of_retries }}"
      until: result is succeeded
      delay: "{{ retry_delay }}"
    - name: download Docker Compose bash completion
      get_url:
        url: "{{ _docker_compose_completion_url }}"
        dest: "/etc/bash_completion.d"
      become: true
      register: result
      retries: "{{ number_of_retries }}"
      until: result is succeeded
      delay: "{{ retry_delay }}"

- name: install Python3 docker module
  pip:
    name: docker
    state: present
    executable: pip3
  become: true
  when: ansible_python.version.major == 3
