# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: create the directory for docker images
  file:
    path: "{{ docker_images_dir }}"
    state: directory
    mode: 0777

- name: create temp directory for docker list
  tempfile:
    state: directory
    prefix: dockerlist-
  register: dockerlist_temp_dir

- name: download list of docker images
  get_url:
    url: "https://{{ hostvars[groups['controller_group'][0]]['ansible_host'] }}/docker_images.yml"
    dest: "{{ dockerlist_temp_dir.path }}"

- name: read docker images list
  slurp:
    src: "{{ dockerlist_temp_dir.path }}/docker_images.yml"
  register: docker_files_encoded

- name: decode docker images list
  set_fact:
    docker_files: "{{ docker_files_encoded['content'] | b64decode }}"

- name: create URLs for packages
  set_fact:
    docker_images: "{{ docker_images | default([]) + ['https://' + hostvars[groups['controller_group'][0]]['ansible_host'] + '/' + item] }}"
  with_items: "{{ docker_files.split('\n') }}"

- name: download docker images
  get_url:
    url: "{{ item }}"
    dest: "{{ docker_images_dir }}"
  with_items: "{{ docker_images }}"

- name: find docker images
  find:
    paths: "{{ docker_images_dir }}"
    patterns: "*.tar*"
  register: docker_image_files

- name: load docker images
  command: "docker load -i {{ item.path }}"
  with_items: "{{ docker_image_files.files }}"
  changed_when: true
