# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: Get python_interpreter
  set_fact: python_interpreter="{{'python3' if ansible_python.version.major == 3 else 'python' }}"

- name: install python os dependencies
  include_role:
    name: infrastructure/install_dependencies
  vars:
    install_dependencies: "{{ os_python_packages[python_interpreter] }}"

- name: Set python to python3
  become: true
  alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/bin/python
  when:
    - python_interpreter == 'python3'

- name: update pip to specified version
  become: true
  pip:
    name: pip
    version: "{{ pip_version }}"

- name: upgrade Python wheel and setuptools
  become: true
  pip:
    name:
      - "wheel=={{ python_wheel_version }}"
      - "setuptools=={{ python_setuptools_version }}"
    extra_args: --upgrade
