# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: configure SELinux
  block:
    - name: set SELinux to disable mode (temporary)
      command: setenforce 0
      failed_when: false
      changed_when: false
      become: true

    - name: set SELinux to permissive mode (pernament)
      selinux:
        policy: targeted
        state: permissive
      become: true
      when: ansible_distribution_version < '8'

    - name: disable SELinux (pernament)
      selinux:
        state: disabled
      become: true
      when: ansible_distribution_version >= '8'
  when: ansible_os_family == "RedHat"
