# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2021 Intel Corporation

---
# Common platform setup playbook
- hosts: controller_group:edgenode_group
  any_errors_fatal: true

  handlers:
    - import_tasks: "{{ playbook_dir }}/../tasks/reboot_server.yml"

  roles:
    - role: infrastructure/setup_offline
    - role: infrastructure/setup_baseline_ansible
    - role: infrastructure/build_noproxy
    - role: baseline_ansible/infrastructure/os_proxy
    - role: infrastructure/os_setup
    - role: baseline_ansible/infrastructure/time_setup_ntp
      when: ntp_enable | default(False)
    - role: baseline_ansible/infrastructure/time_verify_ntp
      reference_host: "{{ groups['controller_group'][0] }}"
      when: "'edgenode_group' in group_names"
    - role: infrastructure/grub

    - role: infrastructure/conditional_reboot
    - role: infrastructure/e810_driver_update
      when: e810_driver_enable | default(False)

    - role: infrastructure/git_repo
    - role: baseline_ansible/infrastructure/install_golang
      offline_role: "{{ ( offline_enable | default(false) ) and ('controller_group' in group_names) }}"
      golang_additional_exports:
        - "export GOPRIVATE=github.com/smart-edge-open"
    - role: infrastructure/docker
