# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
- name: remove collectd config files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ project_dir }}/collectd"
    - "{{ project_dir }}/collectd/configs"
    - "{{ project_dir }}/collectd/pmd"
