# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2021 Intel Corporation

---
- name: download and patch ovs_pmd_stats.py script
  block:
    - name: create temp directory for barometer
      tempfile:
        state: directory
        suffix: barometer
      register: barometer_repo_tmp_dir
      delegate_to: localhost

    - name: checkout repository
      git:
        repo: "{{ _barometer_repo_url }}"
        dest: "{{ barometer_repo_tmp_dir.path }}"
        version: master
        force: true

    - name: make sure repository exists
      git:
        repo: "{{ _barometer_repo_url }}"
        dest: "{{ barometer_repo_tmp_dir.path }}"
        version: master
        update: false

    - name: copy patch file to tmp directory
      copy:
        src: "0001-Remove-whitespace.patch"
        dest: "{{ barometer_repo_tmp_dir.path }}/"
        mode: preserve

    - name: apply patch
      patch:
        src: "{{ barometer_repo_tmp_dir.path }}/0001-Remove-whitespace.patch"
        dest: "{{ barometer_repo_tmp_dir.path }}/3rd_party/ovs_pmd_stats/ovs_pmd_stats.py"
        remote_src: true

    - name: copy patched ovs_pmd_stats.py
      copy:
        src: "{{ barometer_repo_tmp_dir.path }}/3rd_party/ovs_pmd_stats/ovs_pmd_stats.py"
        dest: "{{ project_dir }}/collectd/pmd/"
        mode: preserve
        remote_src: true

    - name: remove temporary directory
      file:
        path: "{{ barometer_repo_tmp_dir.path }}"
        state: absent

    - name: copy ovs pmd scripts
      copy:
        src: "{{ item }}"
        dest: "{{ project_dir }}/collectd/configs/"
        mode: 0755
      with_items:
        - ovs_pmd_stats.sh
        - write_notification.sh
  when: telemetry_flavor == 'corenetwork' or telemetry_flavor == 'smartcity'

- name: create configuration files from templates
  block:
    - name: common configs
      template:
        src: "{{ item }}"
        dest: '{{ project_dir }}/collectd/configs/{{ item | basename | regex_replace("\.j2$", "") }}'
        mode: preserve
      with_fileglob:
        - ../templates/configs/common/*.j2
    - name: telemetry flavor specific
      template:
        src: "{{ item }}"
        dest: '{{ project_dir }}/collectd/configs/{{ item | basename | regex_replace("\.j2$", "") }}'
        mode: preserve
      with_fileglob:
        - ../templates/configs/{{ telemetry_flavor }}/*.j2
      when: telemetry_flavor != 'common'
